Kmw gen style
WilderDev/MemoryBox pull request #21
Opened 2023-12-11 23:30 UTC by H20Beetle

Added gen style, bootstrap reposive design and other styles.

2023-12-11 23:37 UTC, WilderDev approved these changes

2023-12-11 23:40 UTC, WilderDev requested changes
Can you please merge in new changes from staging and resolve conflicts please

2023-12-12 01:14 UTC, gitmissv commented on src/app/core/timecapsule/timecapsuleForm/timecapsule-form.component.html
> -          <div class="form-input">
what happened to First Name?   Looks like First Name was deleted and only LName was updated??

2023-12-12 01:26 UTC, gitmissv approved these changes
Per Kyle - he verified FName is still there - just moved up lines.  vml

2023-12-12 15:03 UTC, Dotwad approved these changes

2023-12-15 01:10 UTC, closed without merging